version: '2.3'

services:
    kafka_consumer_http_target:
        build: ./kafka-consumer-java/
        ports:
            - 4000:4000
        environment:
            - KAFKA_BROKER=kafka:9092
            - TOPIC=test
            - GROUP_ID=test_1
            - SENDING_PROTOCOL=http
            - TARGET=fake-http-server:2000/consume
            - IS_ALIVE_PORT=4000
            - RETRY_TOPIC=test-retry
            - RETRY_PROCESSING_DELAY=10000
        depends_on:
            - kafka
            - fake-http-server

    kafka_consumer_grpc_target:
        build: ./kafka-consumer-java/
        ports:
            - 5000:5000
        environment:
            - KAFKA_BROKER=kafka:9092
            - TOPIC=test
            - GROUP_ID=test_2
            - SENDING_PROTOCOL=grpc
            - TARGET=fake-grpc-server:4770
            - IS_ALIVE_PORT=5000
            - RETRY_TOPIC=test-retry
            - RETRY_PROCESSING_DELAY=10000            
        depends_on:
            - kafka
            - fake-grpc-server

    producer:
        build: ./kafka-producer-java/
        ports:
            - 6000:6000
        environment:
            - PORT=6000
            - KAFKA_BROKER=kafka:9092
            - TOPIC=test

        depends_on:
            - kafka
            - fake-http-server
            
    retry_producer:
        build: ./kafka-producer-java/
        ports:
            - 7000:7000
        environment:
            - PORT=7000
            - KAFKA_BROKER=kafka:9092
            - TOPIC=test-retry

        depends_on:
            - kafka
            - fake-http-server                        

    fake-http-server:
        image: soluto/simple-fake-server
        ports:
            - 3000:3000

    fake-grpc-server:
        image: tkpd/gripmock
        ports:
            - 4770:4770
            - 4771:4771
        volumes:
            - ${PWD}/kafka-consumer-java/src/proto:/proto
        command: /proto/kafkaMessage.proto

    zookeeper:
        image: wurstmeister/zookeeper
        environment:
            - LOG4J_LOGGER_KAFKA=WARN
        ports:
            - '2181:2181'
        logging:
            driver: none

    kafka:
        image: wurstmeister/kafka:2.12-2.2.0
        ports:
            - '9092:9092'
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
            - KAFKA_CREATE_TOPICS=test:2:2,test-retry:1:1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - LOG4J_LOGGER_KAFKA=WARN
        depends_on:
            - zookeeper
        healthcheck:
            test: 'exit 0'
            interval: 15s
            retries: 3
        logging:
            driver: none
