version: '2.3'

services:
    zookeeper:
        image: wurstmeister/zookeeper
        environment:
            - LOG4J_LOGGER_KAFKA=WARN
        logging:
            driver: none

    kafka:
        image: wurstmeister/kafka:2.12-2.2.0
        ports:
            - '9092:9092'
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
            - KAFKA_CREATE_TOPICS=test:10:1,another-test:1:1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - LOG4J_LOGGER_KAFKA=WARN
        depends_on:
            - zookeeper